# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  name: Azure Pipelines
  vmImage: windows-latest
  demands:
  - msbuild
  - visualstudio
  - vstest
  
jobs:
- job: Build
  variables:
    BuildSolution: FibulaMMO.sln
    BuildPlatform: Any CPU
  strategy:
    matrix:
      Debug:
        BuildConfiguration: Debug
        _debugArg: '-Debug'
      Release:
        BuildConfiguration: Release
        _debugArg: ''
  steps:
  - task: NuGetToolInstaller@0
    displayName: 'Use NuGet 5.3.1'
    inputs:
      versionSpec: 5.3.1

  - task: NuGetCommand@2
    displayName: 'NuGet restore'
    inputs:
      restoreSolution: '$(BuildSolution)'
      feedsToUse: 'config'
      nugetConfigPath: 'NuGet.config'
  
  - task: VSBuild@1
    displayName: 'Build solution FibulaMMO.sln'
    inputs:
      solution: '$(BuildSolution)'
      platform: '$(BuildPlatform)'
      configuration: '$(BuildConfiguration)'
      msbuildArgs: '/bl'
      
  - task: PowerShell@2
    displayName: Run Tests
    inputs:
      workingDirectory: '$(Build.SourcesDirectory)/build'
      filePath: build/opencover-report.ps1
      arguments: '$(_debugArg) -NoBuild -NoReport -Azure'

  - task: PublishTestResults@2
    displayName: Publish test results
    inputs:
      testResultsFormat: xUnit
      testResultsFiles: 'build/*.xml'

  - task: PowerShell@2
    displayName: Upload coverage reports to codecov.io
    condition: eq(variables['BuildConfiguration'], 'Debug')
    inputs:
      workingDirectory: '$(Build.SourcesDirectory)/build'
      script: |
        $packageConfig = [xml](Get-Content ..\.nuget\packages.config)
        $codecov_version = $packageConfig.SelectSingleNode('/packages/package[@id="Codecov"]').version
        $codecov = "..\packages\Codecov.$codecov_version\tools\codecov.exe"
        &$codecov -f '..\build\OpenCover.Reports\OpenCover.FibulaMMO.xml'
