# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'                    # other valid values include: 'windows-latest' | 'macOS-latest'

variables:
  BuildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: 'Install .NET Core SDK'
  inputs:
    version: '3.0.x'
    packageType: runtime
    performMultiLevelLookup: true
    includePreviewVersions: true              # Required for preview versions

- task: DotNetCoreCLI@2
  displayName: 'Install Coverlet.Console'
  inputs:
    command: custom
    custom: tool
    arguments: 'install -g coverlet.console'
    
- task: DotNetCoreCLI@2
  displayName: 'Install Codecov.Tool'
  inputs:
    command: custom
    custom: tool
    arguments: 'install -g Codecov.Tool'

- task: NuGetToolInstaller@0
  displayName: 'Use NuGet 5.3.1'
  inputs:
    versionSpec: 5.3.1

- task: NuGetCommand@2
  displayName: 'NuGet restore'
  inputs:
    restoreSolution: '$(BuildSolution)'
    feedsToUse: 'config'
    nugetConfigPath: 'NuGet.config'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: '**/*.csproj'
    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  condition: succeededOrFailed()
  displayName: 'Run Tests'
  inputs:
    workingDirectory: '$(Build.SourcesDirectory)'
    command: test
    projects: '**/*.Tests/*.csproj'
    arguments: '--configuration $(BuildConfiguration) /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=$(Build.SourcesDirectory)/TestResults/Coverage/'
    nobuild: true

- task: PublishCodeCoverageResults@1
  displayName: 'Publish code coverage report'
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '$(Build.SourcesDirectory)/**/coverage.cobertura.xml'
  
- task: PublishTestResults@2
  displayName: 'Publish test results'
  condition: succeededOrFailed()
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'

- script: codecov -f $(Build.SourcesDirectory)/coverage/coverage.covertura.xml
  displayName: 'Upload to CodeCov.io'

- task: PublishCodeCoverageResults@1
  displayName: 'Publish code coverage report'
  inputs:
    codecoverageTool: cobertura
    summaryFileLocation: '$(Build.SourcesDirectory)/coverage/Cobertura/Cobertura.xml'
    reportDirectory: '$(Build.SourcesDirectory)/coverage/Cobertura'
