name: Build (NetCore)

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.101
    - name: Build with dotnet
      run: dotnet build --configuration Release
